### ISSUE TITLE
Add change cause for "Kontemplate apply" 

### ISSUE THREAD

**Issue by ksudheernathreddy** [tazjin/kontemplate#141] opened 2018-06-18 09:17 UTC
Hi,

  We were deploying all our microservices via kontemplate, for each update there could be a change in docker image of one or more microservices. It would be nice if I can add a change cause on kontemplate level, which internally adds change cause for each microservice.

  For example, I want to keep track of application(based on microservices) versions in kubernetes. Even If there is a change in single microservice or more, I will be versioning my application as next version(1.0.0 to 1.1.0). So when I do kontemplate apply for application version 1.1.0, if it adds change cause for all microservices(as 1.1.0), it would be easy to roll back one or more microservices based on revision number(change cause with version name will be associated with it).

Thanks in advance.

**Comment by tazjin** [comment] 2018-10-14 13:42
Closing this as a duplicate of #63. There is technically nothing stopping someone from doing this today, I guess the documentation should have some sort of "Patterns" section for things like this.

**Closed** 2018-10-14 13:43 UTC
Labels: enhancement
