### ISSUE TITLE
1.6 global settings work differently from 1.5 global settings

### ISSUE THREAD

**Issue by agearhart** [tazjin/kontemplate#153] opened 2018-08-15 15:08 UTC
I discovered that 1.6 handles setting overrides differently from 1.5.  Given the following example

---
context: my_awesome_context
global:
  logLevel: debug
include:
  - name: test-service
    values:
      logLevel: warn

version 1.5 will set logLevel to warn and 1.6 will set as debug.

**Comment by tazjin** [comment] 2018-08-15 17:30
Hey! Thanks for filing the report!

This is a duplicate of #142 and fixed in current `master` - please take a look at the discussion in that issue, too.

**Comment by tazjin** [comment] 2018-08-15 19:29
The fix for this is included in [version 1.7.0](https://github.com/tazjin/kontemplate/releases/tag/v1.7.0).

**Closed by tazjin** 2018-08-15 19:29 UTC
Labels: bug, friction-reduction
